README.md
phyloFlash_makedb.pl

ran out of memory with 4 Gb. Increased to 10 Gb

increased memory limit for bbmap.sh in making db reference

---

phyloFlash.pl

fixed bug with filenames that have path component

---

PhyloFlash.pm
phyloFlash.pl
phyloFlash_makedb.pl

passed $cpus variable to all vsearch and bbmap commands

---

PhyloFlash.pm
README.md
phyloFlash.pl
phyloFlash_makedb.pl

also fixes
- some OSX issues
- cpu detection
- error in older Perl Net::FTP
- mafft and bedtools missing in required software documentation
- abort on no rRNA found in spades assembly
- cleanup intermediary files in phyloFlash_makedb.pl (fixes #13)

automatically find suitable dbhome

---

phyloFlash_heatmap.R

fix output file name can't contain multiple dots

---

phyloFlash.pl
phyloFlash_plotscript.R

Turn off insert-size histogram reporting in SE mode
Add short explanations under HTML report headings

Add mapping-identity histogram to report

---

phyloFlash_plotscript.R

Fix plotscript breaks in German locale

Detect decimal separator for locale when reading histogram data

---

phyloFlash.pl
phyloFlash_plotscript.R

* Pretty format phyloFlash_plotscript.R

Add switch `-decimalcomma` for decimal comma to main script

---

phyloFlash_heatmap.R
phyloFlash_plotscript.R

- increase robustness to empty files, NA type values in files, etc.
- allow specifying clustering method for taxa and samples separately
- add fake alphanumeric clustering method (for stable order of samples, e.g.)

increased robustness and alphanumeric sorting

---

PhyloFlash.pm
phyloFlash.pl

Resolve issue #55  - please test

Fix bug with Fasta headers when using bedtools v2.26 or v2.27

---

PhyloFlash.pm
README.md
docs/install.md
docs/output.md
phyloFlash.pl
phyloFlash_report_template.html

* Make bbmap and reformat.sh overwrite existing files of same name
* Document file permissions issue with Vsearch UDB files
* Update version number in script and docs

phyloFlash v3.1 beta 2 dev

---

PhyloFlash.pm
docs/usage.md
phyloFlash.pl
phyloFlash_barplot.R
phyloFlash_compare.pl
phyloFlash_fastgFishing.pl
phyloFlash_makedb.pl

* Remove duplicate code
* Fix documentation typos and missing arguments

Cleanup and documentation fixes

---

phyloFlash.pl

provide proper case for downstream tool.

typo in makedb script name

---

README.md

Also moves the logo to the top right corner

Add some tags to README.md

---

ENA_phyloFlash.pl
PhyloFlash.pm
README.md
docs/FAQ.md
docs/index.md
docs/install.md
phyloFlash.pl
phyloFlash_compare.pl
phyloFlash_fastgFishing.pl
phyloFlash_makedb.pl
phyloFlash_plotscript_svg.pl

* Update docs with installation by Conda
* Update copyright year
* Detect when zero reads mapped (Issue #77 ) and exit with error message instead of crashing

Update docs, detect zero reads mapped

---

README.md
docs/usage.md
phyloFlash.pl
phyloFlash_makedb.pl
phyloFlash_report_template.html

* Let dbhome be given by environment variable, partly in response to issue #83 
* Add preprint citation to report template

dbhome via environment variable

---

README.md
docs/index.md
docs/install.md

Document workaround for conda solving environment hang

---

phyloFlash.pl

Running phyloFlash with single end reads led to the following error:
```
[12:28:23] Reading remappings to summarize taxonomy of unmapped reads
[12:28:23] Reading results of remapping to SPAdes results
[12:28:23] total fwd reads remapping:8900
Illegal division by zero at /local/home/rpetit3/repos/phyloFlash/phyloFlash.pl line 1961.
```
This was due to not counting remapped reads for single end reads due to the flags being different then the paired end reads.
Also, if CHAO becomes the string 'n.d.' the following warning is produced.
```
Argument "n.d." isn't numeric in sprintf
```
Added logic to only use sprintf if $chao1 is not equal to 'n.d.'

Improved single end support

---

PhyloFlash.pm
README.md
docs/index.md
docs/install.md
phyloFlash.pl

nhmmer mapping step (to check evenness of coverage across SSU gene model) was not accounting for SE or interleaved reads, should be fixed by this PE

Fix bug in using SE reads 

---

docs/utilities.md

Document usage of ntu_table task in phyloFlash_compare.pl script

---

PhyloFlash.pm
README.md
docs/FAQ.md
docs/index.md
docs/install.md
docs/multiple-samples.md
docs/output.md
docs/usage.md
docs/utilities.md
phyloFlash.pl
phyloFlash_makedb.pl

Implement some requested features: 
* User can change database ref min length (issues #117 , #115 )
* Auto-detect read length from read files (issue #67 )

Auto detect read length and change database min length

---

README.md
docs/index.md
docs/install.md
phyloFlash.pl

Users hvae reported problems with installing phyloFlash to an existing
conda env as described in docs. Changed docs to recommend creating a new
env and installing packages at the same time.

Update conda installation command in docs
